apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-watcher-sa
  namespace: dung-crds-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-watcher-role
  namespace: dung-crds-test
  labels:
    "app.kubernetes.io/name": 'api-watcher-role'
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["create","delete","get","list","patch","update","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-watcher-role-binding
  namespace: dung-crds-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-watcher-role
subjects:
- kind: ServiceAccount
  name: api-watcher-sa
  namespace: dung-crds-test