apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: informationz.vtdc.local
spec:
  scope: Namespaced
  group: vtdc.local
  names:
    kind: InforZ
    plural: informationz
    singular: infor
    shortNames:
      - infz
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: data
          type: integer
          priority: 1
          jsonPath: .spec.data
          description: values of data
        - name: personal
          type: string
          priority: 1
          jsonPath: .spec.personal
          description: personal
        - name: gitrepo
          type: string
          priority: 1
          jsonPath: .spec.gitrepo
          description: Git repository with web content
